### PR TITLE
Use Azure for apps instead of Heroku

### PR DESCRIPTION
**Pull request by doaa-altarawy**
Apps are in iFrames from:
http://qcarchive-webapps.eastus.cloudapp.azure.com/

Instead of Heroku.

Once this PR is merged, the production deployment is done.

### CODE REVIEW

**Comment by doaa-altarawy** [comment]
@dgasmith Is there an easy way to use HTTPS in Azure?

**Comment by dgasmith** [comment]
@doaa-altarawy Lets encrypt like normal. Since we own the VM and DNS it should be easy.

**Comment by doaa-altarawy** [comment]
I mean through Azure, like Heroku does.

**Comment by dgasmith** [comment]
Heroku is a full featured service for web apps that comes with limitations. We provisioned a raw VM from Azure so we should use lets encrypt. Alternatively you could look at deploying on their web app service which is similar to Heroku which may come with TLS.

**Comment by dgasmith** [comment]
@doaa-altarawy @mattwelborn This is awesome! Ton of hard work here and the preview looks great.

The only item that I noticed isn't working is that for some reason the iFrame links do not appear to take us anywhere. @doaa-altarawy any comments there?

**Comment by doaa-altarawy** [comment]
Yes, I can see Github links don't work inside the RDS iFrame. It's actually GitHub that prevents iframing their pages, nothing can be done about that. So we need to open those links in a new page.
@mattwelborn can you update the links to use HTML instead of Markdown in the RDS?

**Comment by dgasmith** [comment]
I don't think its GitHub if you modify the html targets with a `<base>` in the `<head>` you can get the links to work just fine and the issue happens on the DOI links as well. Is there anyway we can inject a:

```html
<head>
  ...
  <base target="_blank">
</head>
```?

**Comment by doaa-altarawy** [comment]
I don't know if the head of the Dash template is accessible.
For replacing Markdown, can we replace it with Dash HTML components not raw HTML?

**Comment by dgasmith** [comment]
I didn't get an understanding of how to add a `a` tag inside a `p` tag from the following: https://dash.plot.ly/dash-html-components

**Comment by dgasmith** [comment]
Of course: https://community.plot.ly/t/dash-html-a-tags-within-html-p-tags/18367

**Comment by doaa-altarawy** [comment]
The DOI error is:
```
Mixed Content: The page at 'https://deploy-preview-75--qcarchive-molssi.netlify.com/apps/reaction_viewer/' was loaded over HTTPS, but requested an insecure resource 'http://xlink.rsc.org/?DOI=B600027D'. This request has been blocked; the content must be served over HTTPS.
```

The Github error is:
```
Refused to display 'https://github.com/MolSSI/MQCAS/issues/new/choose' in a frame because an ancestor violates the following Content Security Policy directive: "frame-ancestors 'none'".
```

**Comment by dgasmith** [comment]
See here: https://github.com/MolSSI/QCArchiveWebapps/pull/69

**Pull request merged**
