### PR TITLE
Add dash apps to the website

### PR DESCRIPTION
**Pull request by doaa-altarawy**
Add Dash apps link in the website.
Apps are displayed in an iFrame.

## Status
- [x] Ready to go

### CODE REVIEW

**Comment by dgasmith** [comment]
This is super cool!

image

**Comment by doaa-altarawy** [comment]
@dgasmith  ready for review.

**Comment by dgasmith** [comment]
The Deploy preview seems rough, perhaps due to the JS change? We ended up needing to rebuild the SASS and committing it as Netlify will not build it for us. Can we also turn off reaction dataset for now, it does not appear to work and I need to put a big "Alpha state" banner across the top.

We also need to figure out some sort of header bar separation. @ishunko Can you look at the deploy preview here, go to Apps on the main header, and click on ML datasets in the main dropdown. The header and the app blend together too much, do you have any ideas to separate these?

**Comment by doaa-altarawy** [comment]
Done. Can you merge the PR so that we work on other PRs

**Comment by ishunko** [comment]
I made a PR with possible suggested header separation styles: https://github.com/MolSSI/QCArchiveWebsite/pull/61

**Pull request merged**
