### PR TITLE
Add blog post for Queue Manager discussion

### PR DESCRIPTION
**Pull request by Lnaden**
Still have some placeholders, but something to start with.

### CODE REVIEW

**Comment by dgasmith** [comment]
See further discussion [here](https://docs.google.com/document/d/1a_IQPjmApeHd56az_PYAVaHHNVx4S-oEH4EzjiqykFk/edit). Please note that this is not public access, but can be requested.

**Comment by Lnaden** [comment]
@dgasmith I have made another pass through the edits, it was some small clarity edits and one or two grammatical fixes. I think this is ready so I have updated the PR here.

**Comment by dgasmith** [comment]
Looks good, please copy it over and push this out.

**Comment by Lnaden** [comment]
I copied it over in 9af7a4b

**Pull request merged**
