### PR TITLE
Update blog post ACS

### PR DESCRIPTION
**Pull request by Lnaden**
* Renamed blog files to be more relevant
    * Added alias to the 2 old ones so old hyperlinks still work and redirect to new ones
* Added promo video to the home page again
* Updated blog with ACS talk

### CODE REVIEW

**Comment by Lnaden** [comment]
qcablackback

The homepage gets an additional section linking to the YouTube video with this as the background for the section. which appears as a static background layer where the page itself moves past it for that section.

**Comment by Lnaden** [comment]
Yeah, I just inverted the colors on everything but the blue bits

**Comment by dgasmith** [comment]
Looking at it again, maybe we just have the dark background? Becomes hard to read when the QCArchive bit slides across.

**Comment by Lnaden** [comment]
That was the question I had. I can make it a flat black, not sure if it needs to be more interesting than that though. I'll tinker with it a bit.

**Pull request merged**
