### PR TITLE
Another drop shadpow take on the logo

### PR DESCRIPTION
**Pull request by Lnaden**
Added drop shadow variant 2 to the git

### CODE REVIEW

**Comment by Lnaden** [comment]
Fighting with SVG's is fun!

**Comment by dgasmith** [comment]
At 159Kb the png is too big to be useful. Does it need to be there?

**Comment by Lnaden** [comment]
No, I'll shrink it and merge the commits down so as not to add the file.

**Comment by Lnaden** [comment]
Squashed, now ~60kb png

**Comment by dgasmith** [comment]
Still pretty massive for an image, any real reason to keep it that big?

**Comment by Lnaden** [comment]
Its in line with the size of the images from the example site. This one is the banner header so will be larger than the rest, its also only the backup image if the first one can't load so will not be served to all the people... I think?

**Pull request merged**
